"""
GUI 套件主入口
"""

from constants import (
    # 檔案系統
    CONFIG_DIR,
    PROJECT_SETTINGS_FILENAME,
    DIR_IMAGES,
    DIR_REPORTS,
    DEFAULT_DESKTOP_PATH,
    # 專案類型
    PROJECT_TYPE_FULL,
    PROJECT_TYPE_ADHOC,
    DEFAULT_TESTER_NAME,
    DEFAULT_ADHOC_PREFIX,
    # 日期格式
    DATE_FMT_PY_DATE,
    DATE_FMT_PY_DATETIME,
    DATE_FMT_PY_FILENAME,
    DATE_FMT_PY_FILENAME_SHORT,
    DATE_FMT_QT,
    # 狀態
    STATUS_PASS,
    STATUS_FAIL,
    STATUS_NA,
    STATUS_UNCHECKED,
    STATUS_NOT_TESTED,
    STATUS_UNKNOWN,
    # 顏色
    COLOR_BG_PASS,
    COLOR_BG_FAIL,
    COLOR_BG_NA,
    COLOR_BG_DEFAULT,
    COLOR_BTN_ACTIVE,
    COLOR_TEXT_PASS,
    COLOR_TEXT_FAIL,
    COLOR_TEXT_GRAY,
    COLOR_TEXT_WHITE,
    # 目標
    TARGET_UAV,
    TARGET_GCS,
    TARGETS,
    PHOTO_ANGLES_ORDER,
    PHOTO_ANGLES_NAME,
)

from styles import THEME, Styles

__all__ = [
    # Constants
    "CONFIG_DIR",
    "PROJECT_SETTINGS_FILENAME",
    "DIR_IMAGES",
    "DIR_REPORTS",
    "DEFAULT_DESKTOP_PATH",
    "PROJECT_TYPE_FULL",
    "PROJECT_TYPE_ADHOC",
    "DEFAULT_TESTER_NAME",
    "DEFAULT_ADHOC_PREFIX",
    "DATE_FMT_PY_DATE",
    "DATE_FMT_PY_DATETIME",
    "DATE_FMT_PY_FILENAME",
    "DATE_FMT_PY_FILENAME_SHORT",
    "DATE_FMT_QT",
    "STATUS_PASS",
    "STATUS_FAIL",
    "STATUS_NA",
    "STATUS_UNCHECKED",
    "STATUS_NOT_TESTED",
    "STATUS_UNKNOWN",
    "COLOR_BG_PASS",
    "COLOR_BG_FAIL",
    "COLOR_BG_NA",
    "COLOR_BG_DEFAULT",
    "COLOR_BTN_ACTIVE",
    "COLOR_TEXT_PASS",
    "COLOR_TEXT_FAIL",
    "COLOR_TEXT_GRAY",
    "COLOR_TEXT_WHITE",
    "TARGET_UAV",
    "TARGET_GCS",
    "TARGETS",
    "PHOTO_ANGLES_ORDER",
    "PHOTO_ANGLES_NAME",
    # Styles
    "THEME",
    "Styles",
]
